### PR TITLE
[93] Add special (non-draw) group creation

### LINKED ISSUE #93: Admins can manually create groups outside of draws
This is for exceptional case handling outside of draws, we want them to be able to create ad-hoc groups of students and assign said groups to suites. We can use our existing data models as long as we remove the `validate :draw, presence: true` from groups and then everything else should be fine.

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #93
- Add root-level groups resource handled by SpecialGroupsController
- Add SpecialGroup wrapper/delegator class so that we can use different permissions for the SpecialGroupsController
- Add SuiteSizesQuery to get all unique suite sizes in a given relation
- Add SpecialGroupCreator service object to ignore draw logic
- Split up groups _form partial for reuse in special_groups _form

### CODE REVIEW

File: app/models/group.rb [hunk 1]
```diff
@@ -10,18 +10,17 @@
 class Group < ApplicationRecord
   belongs_to :leader, class_name: 'User'
   belongs_to :draw
-  has_many :memberships
+  has_many :memberships, dependent: :delete_all
```
Comment (orenyk) [inline app/models/group.rb]: Should we test this somehow? It's pretty lucky that I caught it by just playing with the app manually... a good reminder that automated tests don't always cover every aspect of the app. Where would this test go? On the model? e.g.

```ruby
it 'destroys dependent memberships` do
  group = FactoryGirl.create(:special_group)
  memberships = group.memberships
  group.destroy
  expect(Membership.find(memberships.map(&:id))).to be_empty
end
```

I guess that could work, let me know what you think and I'll add it (and we can do something similar for users).

**Comment by orenyk** [comment]
@esoterik finally ready! It's a bit of a doozy, though, but hopefully I've covered all the edge cases. ~~See my note about testing `dependent: :delete` for our membership associations, I can add it pretty easily.~~ I'm just going to add it and re-push.

File: app/models/group.rb (hunk 1 above)
Comment (orenyk) [inline app/models/group.rb]: Nvm, I added these specs to the model specs for both user and group.

File: app/models/user.rb [hunk 2]
```diff
@@ -7,7 +7,7 @@ class User < ApplicationRecord
          :recoverable, :rememberable, :trackable, :validatable
 
   belongs_to :draw
-  has_one :membership
+  has_one :membership, dependent: :destroy
```
Comment (orenyk) [inline app/models/user.rb]: Note that we can use `dependent: :destroy` here since the group isn't destroyed when a user is hypothetically destroyed. This will ensure that all the membership / group callbacks are correctly called.

File: app/models/group.rb (hunk 1 above)
Comment (orenyk) [inline app/models/group.rb]: Note the use of `delete_all` due to callback loops when `destroy` was used (group is being destroyed, it calls destroy on the membership, which attempts to update the group and it gets messy and broken).

File: app/controllers/special_groups_controller.rb [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+
+  def destroy
+    result = Destroyer.new(object: @group, name_method: :name).destroy
+    handle_action(**result)
+  end
+
+  private
+
+  def authorize!
+    @group ? authorize(SpecialGroup.new(@group)) : authorize(SpecialGroup)
```
Comment (esoterik) [inline app/controllers/special_groups_controller.rb]: do you prefer the ternary syntax for these?

File: app/controllers/special_groups_controller.rb [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+  def special_group_params
+    params.require(:group).permit(:size, :leader_id, member_ids: [])
+  end
+
+  def set_group
+    @group = Group.find(params[:id])
+  end
+
+  def set_form_data
+    @group ||= Group.new
```
Comment (esoterik) [inline app/controllers/special_groups_controller.rb]: this is nice!!

File: app/models/group.rb [hunk 5]
```diff
@@ -47,6 +46,16 @@ def add_leader_to_members
...
 
+  def validate_suite_size_inclusion
+    if draw.present?
+      return if draw.suite_sizes.include? size
+      errors.add :size, 'must be a suite size included in the draw'
+    else
+      return if SuiteSizesQuery.call.include? size
+      errors.add :size, 'must be a valid suite size'
+    end
+  end
```
Comment (esoterik) [inline app/models/group.rb]: if we end up with more draw presence conditionals, we should consider creating a `DrawlessGroup` object to contain all of this behavior, but this is fine for now

Comment (esoterik) [inline app/models/group.rb]: (this is maybe worth commenting somewhere?)

File: app/controllers/special_groups_controller.rb (hunk 3 above)
Comment (orenyk) [inline app/controllers/special_groups_controller.rb]: It's more concise, so I figured why not. What do you think?

File: app/controllers/special_groups_controller.rb (hunk 4 above)
Comment (orenyk) [inline app/controllers/special_groups_controller.rb]: It was born of necessity 😄. Rubocop / code smells for the win!

File: app/models/group.rb (hunk 5 above)
Comment (orenyk) [inline app/models/group.rb]: Yea... excellent catch. I'll add a comment to this validation method (maybe with a TODO header just to keep us on our toes). Let me know what you think!

File: app/services/creators/special_group_creator.rb [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+
+  def process_params
+    @params = params.to_h.transform_keys(&:to_sym)
+    remove_blank_members if params[:member_ids]
+    remove_members_and_leader_from_draw
+  end
+
+  def remove_blank_members
+    @params[:member_ids] = params[:member_ids].reject(&:empty?)
+  end
```
Comment (orenyk) [inline app/services/creators/special_group_creator.rb]: Hmm, the alternative could be just to use GroupCreator and add some `draw.present?` logic? I'll ping you on Slack to discuss.

**Comment by orenyk** [comment]
I'm also going to add some logic to the service object to switch intents to `on_campus`, good catch!

**Comment by orenyk** [comment]
@esoterik how's this? I still haven't updated the `DrawlessGroupsPolicy`, but we can leave it for now and open a new issue if you'd like to adjust those permissions. Let me know!
