### PR TITLE
[545] Allow reps to view the draw page during suite selection

### LINKED ISSUE #545: Fix broken selection metrics for reps during suite selection phase
## Backtrace

    line 263 of [PROJECT_ROOT]/app/controllers/draws_controller.rb: calculate_selection_metrics
    line 11 of [PROJECT_ROOT]/app/controllers/draws_controller.rb: show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50268/faults/33171663)

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #545

### CODE REVIEW

File: spec/policies/draw_policy_spec.rb [hunk 1]
```diff
@@ -481,4 +481,43 @@
       end
     end
   end
+
+  context 'role-agnostict permissions' do
```
Comment (esoterik) [inline spec/policies/draw_policy_spec.rb]: typo
