### PR TITLE
[224] Add oversubscription handling to draws

### LINKED ISSUE #224: Admins can disband oversubscribed groups following confirmation
Add an oversubscription handling page (linked to during the confirmation in #183) that allows admins to disband select groups in oversubscribed sizes.

1. This can be a page listing all groups broken down by size with a button to disband (JS confirmation, policy to show).
2. We can highlight oversubscribed sizes (background color).
3. We should also have a button to lock a specific suite size (policy-based).
4. List # of groups and # of suites for each size at the start of each section

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #224
- Redirect lottery start requests to oversubscription page if draw is oversubscribed, but can be bypassed even while oversubscribed
- Add Draw#oversubscribed? and Draw#size_locked?
- Add GroupSizesQuery
- Add DrawSizesQuery (yay Arel)
- Allow group disbanding requests to take a path to redirect to
- Add draw size locking route (also takes a redirect path via params)
- Add DrawsHelper#toggle_size_lock_btn

### CODE REVIEW

**Comment by orenyk** [comment]
Codeclimate's complaining about duplicate code, otherwise should be good for review.

File: app/controllers/draws_controller.rb [hunk 1]
```diff
@@ -222,4 +207,34 @@ def prepare_students_edit_data
...
+    result = DrawStudentsUpdate.update(draw: @draw,
+                                       params: students_update_params)
+    @students_update = result[:update_object]
+    if @students_update
+      prepare_students_edit_data
+      result[:action] = 'student_summary'
+    else
+      result[:path] = student_summary_draw_path(@draw)
+    end
+    result
```
Comment (esoterik) [inline app/controllers/draws_controller.rb]: I don't really like the duplication between here and the next method

File: app/models/draw.rb [hunk 2]
```diff
@@ -69,7 +70,8 @@ def groups?
   #
   # @return [Boolean] whether or not there are any ungrouped students
   def ungrouped_students?
-    students.includes(:group).select { |s| s.group.nil? }.count.positive?
+    students.on_campus.includes(:group)
+            .select { |s| s.group.nil? }.count.positive?
```
Comment (esoterik) [inline app/models/draw.rb]: this should use a query object and include undeclared students?

File: app/services/draw_size_lock_toggler.rb [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+  def integer_string?(size_str)
+    /^\d+$/.match(size_str)
+  end
+
+  def valid?
+    unless draw
+      errors << 'You must pass a draw'
+      return false
+    end
+    errors << 'Suite size unavailable' unless draw.suite_sizes.include?(size)
```
Comment (esoterik) [inline app/services/draw_size_lock_toggler.rb]: this is unnecessary

File: app/services/draw_size_lock_toggler.rb [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+  def parse_size(size_str)
+    errors << 'Size must be an integer' unless integer_string?(size_str)
+    size_str.to_i
+  end
+
+  def integer_string?(size_str)
+    /^\d+$/.match(size_str)
+  end
+
+  def valid?
```
Comment (esoterik) [inline app/services/draw_size_lock_toggler.rb]: actually none of these are necessary

File: app/services/draw_size_lock_toggler.rb [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+  # permit calling :toggle on the base class
+  def self.toggle(**params)
+    new(**params).toggle
+  end
+
+  # Initialize a new DrawSizeLockToggler
+  #
+  # @param draw [Draw] the draw in question
+  # @param size_str [String] the size param passed in the request
+  def initialize(draw:, size_str:)
```
Comment (esoterik) [inline app/services/draw_size_lock_toggler.rb]: the name `size_str` is confusing given `Suite.size_str`

File: app/models/draw.rb (hunk 2 above)
Comment (orenyk) [inline app/models/draw.rb]: done

**Comment by orenyk** [comment]
I've refactored the lottery validations as per our discussion and the comments in #344, still have to address the other comments.

File: app/services/draw_size_lock_toggler.rb (hunk 5 above)
Comment (orenyk) [inline app/services/draw_size_lock_toggler.rb]: can I just call it `size` even though `@size` is the integer?

File: app/services/draw_size_lock_toggler.rb (hunk 4 above)
Comment (orenyk) [inline app/services/draw_size_lock_toggler.rb]: :+1:

File: app/services/draw_size_lock_toggler.rb (hunk 3 above)
Comment (orenyk) [inline app/services/draw_size_lock_toggler.rb]: :+1:

File: app/controllers/draws_controller.rb (hunk 1 above)
Comment (orenyk) [inline app/controllers/draws_controller.rb]: That is an excellent point, but since this was just a simple move I think we should add that to Refactoring.

**Comment by orenyk** [comment]
@esoterik ready for re-review!

**Comment by orenyk** [comment]
I also rebased after merging #344, hopefully I didn't break anything since there were a number of merge conflicts. Fingers crossed!

File: app/controllers/draws_controller.rb [hunk 6]
```diff
@@ -91,38 +91,26 @@ def students_update
...
-                                       params: students_update_params)
-    @students_update = result[:update_object]
-    if @students_update
-      prepare_students_edit_data
-      result[:action] = 'student_summary'
-    else
-      result[:path] = student_summary_draw_path(@draw)
+  def start_lottery
+    @lottery_starter = DrawLotteryStarter.new(draw: @draw)
+    if handle_oversubscription?
```
Comment (esoterik) [inline app/controllers/draws_controller.rb]: can we actually just conditionally change the "Proceed to Lottery" button to a "Proceed to Oversubscription" instead of this?

File: app/views/draws/_oversub_report.html.erb [hunk 7]
```diff
@@ -1,4 +1,5 @@
 <h3>Draw Summary</h3>
+<%= link_to 'Handle Oversubscription', oversub_draw_path(draw), class: 'button' if draw.oversubscribed? %>
```
Comment (esoterik) [inline app/views/draws/_oversub_report.html.erb]: this needs to validate that all groups in an oversubscribed size are locked before proceeding

File: app/views/draws/oversubscription.html.erb [hunk 8]
```diff
@@ -0,0 +1,8 @@
+<h1><%= @draw.name %> - Oversubscription handling</h1>
+<div class="group-report">
+  <%= render 'group_report', sizes: @draw_sizes, groups: @groups_by_size, actions_partial: 'groups/actions', path: oversub_draw_path(@draw) %>
+</div>
+<% if policy(@draw).start_lottery? && @proceeding_to_lottery %>
+  <p><%= link_to 'Really proceed to lottery', start_lottery_draw_path(@draw, force: '1'), method: :patch, class: 'button alert' %></p>
+<% end %>
```
Comment (esoterik) [inline app/views/draws/oversubscription.html.erb]: this should have a tooltip with a warning

File: app/policies/draw_policy.rb [hunk 9]
```diff
@@ -58,6 +58,14 @@ def start_lottery?
     edit? && record.pre_lottery?
   end
 
+  def oversubscription?
+    start_lottery?
```
Comment (orenyk) [inline app/policies/draw_policy.rb]: Validate that all groups in an oversubscribed size are locked and that we have oversubscription at all.

File: app/views/draws/_oversub_report.html.erb (hunk 7 above)
Comment (orenyk) [inline app/views/draws/_oversub_report.html.erb]: Make this button not blue

File: app/controllers/draws_controller.rb (hunk 6 above)
Comment (orenyk) [inline app/controllers/draws_controller.rb]: Make the proceed to oversubscription button red --> more helpers!

File: app/views/draws/oversubscription.html.erb (hunk 8 above)
Comment (orenyk) [inline app/views/draws/oversubscription.html.erb]: This is blocked on #364

File: app/services/draw_size_lock_toggler.rb [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+    error(draw.errors.full_messages.join(', '))
+  end
+
+  private
+
+  attr_reader :draw, :size
+  attr_accessor :errors
+
+  def parse_size(size)
+    errors << 'Invalid size' unless integer_string?(size)
```
Comment (esoterik) [inline app/services/draw_size_lock_toggler.rb]: can this error message be `"Invalid size #{size}" instead?

File: app/services/draw_size_lock_toggler.rb [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+    /^\d+$/.match(size)
+  end
+
+  def valid?
+    errors.empty?
+  end
+
+  def toggle_size_lock
+    if draw.size_locked?(size)
+      draw.locked_sizes.delete_if { |s| s == size }
```
Comment (esoterik) [inline app/services/draw_size_lock_toggler.rb]: I suppose we don't validate that the sizes are unique within `locked_sizes` so that's why we can't just use `delete(size)` here

File: app/helpers/draws_helper.rb [hunk 12]
```diff
@@ -22,9 +22,50 @@ def diff_class(diff)
...
 
   def day_str(n)
     "#{n} #{'day'.pluralize(n)}"
   end
+
+  def lock_size_btn(draw, size, path)
+    link_to "Lock #{size_str_proper(size)}",
+            toggle_size_lock_draw_path(draw, size, redirect_path: path),
+            method: :patch, id: "lock-size-#{size}", class: 'button'
+  end
```
Comment (esoterik) [inline app/helpers/draws_helper.rb]: can we add a descriptive tooltip ("Prevent students from forming more groups of this size")?

File: app/helpers/draws_helper.rb [hunk 13]
```diff
@@ -22,9 +22,50 @@ def diff_class(diff)
...
+
+  def unlock_size_btn(draw, size, path)
+    link_to "Unlock #{size_str_proper(size)}",
+            toggle_size_lock_draw_path(draw, size, redirect_path: path),
+            method: :patch, id: "unlock-size-#{size}", class: 'button'
+  end
```
Comment (esoterik) [inline app/helpers/draws_helper.rb]: this one should be "Allow students to form groups of this size")

File: app/helpers/draws_helper.rb [hunk 14]
```diff
@@ -22,9 +22,50 @@ def diff_class(diff)
...
+
+  def size_str_proper(size)
+    size_str(size).pluralize.capitalize
+  end
```
Comment (esoterik) [inline app/helpers/draws_helper.rb]: should this live in `ApplicationHelper`? I feel like we use it a lot

also I think it should be named something else -- `headerize_size` or something?

File: app/models/draw.rb [hunk 15]
```diff
@@ -122,6 +123,24 @@ def lottery_complete?
     groups.all? { |g| g.lottery_number.present? }
   end
 
+  # Query method to check whether or not a draw is oversubscribed by checking
+  # all groups. Memoized to avoid querying multiple times per request.
+  #
+  # @return [Boolean] whether or not the draw is oversubscribed
+  def oversubscribed?
+    @oversubscribed ||= GroupSizesQuery.new(groups).call.any? do |size|
+      groups.where(size: size).count > suites.where(size: size).count
```
Comment (orenyk) [inline app/models/draw.rb]: Yea I guess they could be scopes but I'm not sure how much you benefit from that (it's a pretty self-explanatory query). Either way, if you feel strongly open up a refactoring issue.

File: app/policies/draw_policy.rb [hunk 16]
```diff
@@ -62,6 +62,14 @@ def start_lottery?
...
+  end
+
+  def size_lock?
```
Comment (orenyk) [inline app/policies/draw_policy.rb]: lol good cal.

Comment (orenyk) [inline app/policies/draw_policy.rb]: Oh wait, I didn't do that since the same route is used to unlock the size, but admittedly size_lock is also confusing. We can use `toggle_size_lock` but it's just messy. What do you think?

File: app/services/draw_lottery_starter.rb [hunk 17]
```diff
@@ -54,11 +55,16 @@ def at_least_one_group
     errors.add(:draw, 'must have at least one group')
   end
 
-  def no_ungrouped_students
-    return unless draw.present? && draw.ungrouped_students?
+  def all_students_grouped
+    return if draw.nil? || draw.all_students_grouped?
```
Comment (orenyk) [inline app/services/draw_lottery_starter.rb]: good catch

Comment (orenyk) [inline app/services/draw_lottery_starter.rb]: Turns out some of the specs were broken but still passing, either way fixed now.

File: app/services/draw_size_lock_toggler.rb (hunk 11 above)
Comment (orenyk) [inline app/services/draw_size_lock_toggler.rb]: Yup, I'm not sure that was 100% intentional but you're right, we couldn't do it the other way.

**Comment by orenyk** [comment]
Back to you @esoterik, just needs to be squashed / rebased.

File: app/views/draws/oversubscription.html.erb [hunk 18]
```diff
@@ -0,0 +1,10 @@
+<h1><%= @draw.name %> - Oversubscription handling</h1>
+<div class="group-report">
+  <%= render 'group_report', sizes: @draw_sizes, groups: @groups_by_size, actions_partial: 'groups/actions', path: oversub_draw_path(@draw) %>
+</div>
+<% if policy(@draw).start_lottery? && @proceeding_to_lottery %>
+  <p><%= link_to 'Really proceed to lottery', start_lottery_draw_path(@draw), method: :patch, class: 'button alert',
+                 **with_tooltip(text: 'Clicking this button will proceed to the lottery phase, even if there are still oversubscribed suite sizes!',
+                                class_override: 'button alert') %></p>
```
Comment (esoterik) [inline app/views/draws/oversubscription.html.erb]: it's a bit confusing to have this button disappear after oversubscription is resolved, but it makes sense because there will be ungrouped students after disbanding groups to resolve oversubscription. 

not really sure how we should fix this

File: app/models/draw.rb [hunk 19]
```diff
@@ -65,12 +66,12 @@ def groups?
...
+  # Query method to see if all on-campus students in the draw are in groups
   #
-  # @return [Boolean] whether or not there are any ungrouped students
-  def ungrouped_students?
-    students.where(intent: %w(on_campus undeclared)).includes(:group)
-            .select { |s| s.group.nil? }.count.positive?
+  # @return [Boolean] whether or not all on-campus students are in groups
+  def all_students_grouped?
+    @relevant_students ||= students.where(intent: %w(undeclared on_campus))
+    UngroupedStudentsQuery.new(@relevant_students).call.count.zero?
```
Comment (orenyk) [inline app/models/draw.rb]: Oh yea that makes more sense 😛

**Comment by orenyk** [comment]
A bunch of minor changes as discussed, ready for another review!

File: app/views/draws/_group_report.html.erb [hunk 20]
```diff
@@ -2,24 +2,31 @@
...
-          <tr id="group-<%= group.id %>">
-            <td data-role="group-leader"><%= group.leader.full_name %></td>
-            <td data-role="group-status"><%= group.status.capitalize %></td>
-            <td data-role="group-actions"><%= render actions_partial, group: group %></td>
-          </tr>
-        <% end %>
-      </tbody>
-    </table>
+    <div class="groups-<%= size %>">
+      <h4><span class="group-size-header <%= diff_class(diff[size]) %>"><%= headerize_size(size) %> <%= " - #{pluralize(suite_counts[size], 'suite')}, #{pluralize(group_counts[size], 'group')}" %><%= ' (locked)' if @draw.size_locked?(size) %></span></h4>
```
Comment (esoterik) [inline app/views/draws/_group_report.html.erb]: I don't really love how this looks but I'm going to just open up a low priority issue to fix it so we can merge this
