### PR TITLE
[148] Ensure membership errors display correctly

### LINKED ISSUE #148: Membership Errors should be more specific
Right now, when group creation fails because the memberships are invalid, the only error shown is "Memberships invalid" which isn't helpful. We should figure out how to get the more specific membership errors into the flash.

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #148
- Check membership validity before validating a group
- Change create / update actions to rendering responses instead of
  redirecting for groups
- Fix bug in GroupsController#create that prevented group errors from
  being displayed after invalid submission
- Tweak group creator to properly handle invalid params
- Fix all the ensuing bugs :-\

### CODE REVIEW

**Comment by orenyk** [comment]
That's not actually a regression - it's broken on master. This is actually kinda expected - the size validation won't fail until the full memberships are all persisted, which can never happen. Not sure how to resolve this... we could add a separate non-ActiveModel validation for size instead, if you'd like. Thoughts?

File: app/models/group.rb [hunk 1]
```diff
@@ -124,6 +126,15 @@ def add_leader_to_members
     members << leader unless members.include? leader
   end
 
+  # rubocop:disable RaiseArgs
+  def check_full_membership_validity
```
Comment (esoterik) [inline app/models/group.rb]: why isn't this just the first validation? we can have it stop the callback chain and not validate further, i think, and that way we can customize the error message

Comment (orenyk) [inline app/models/group.rb]: Ohh rather than raising an exception? Maybe, let's chat about it offline and figure it out from there.
